repos:
- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: flake8 gentile --count --show-source --statistics
    pass_filenames: false
    language: system
  - id: mypy
    name: mypy
    entry: mypy gentile
    pass_filenames: false
    language: system