# Generated by Django 4.0.3 on 2022-03-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=30)),
                ('iso', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=50)),
                ('gentile_fr', models.CharField(max_length=100)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gentile.canton')),
            ],
        ),
    ]
