# Generated by Django 4.0.3 on 2022-03-18 19:10

from django.db import migrations


def seed_from_data(apps, schema_editor):
    Canton = apps.get_model('gentile', 'Canton')
    Commune = apps.get_model('gentile', 'Commune')

    for iso, name_fr in (
        ('AR', 'Appenzell Rhodes-Extérieures'),
        ('AI', 'Appenzell Rhodes-Intérieures'),
        ('AG', 'Argovie'),
        ('BL', 'Bâle-Campagne'),
        ('BS', 'Bâle-Ville'),
        ('BE', 'Berne'),
        ('FR', 'Fribourg'),
        ('GE', 'Genève'),
        ('GL', 'Glaris'),
        ('GR', 'Grisons'),
        ('JU', 'Jura'),
        ('LU', 'Lucerne'),
        ('NE', 'Neuchâtel'),
        ('NW', 'Nidwald'),
        ('OW', 'Obwald'),
        ('SG', 'Saint-Gall'),
        ('SH', 'Schaffhouse'),
        ('SZ', 'Schwytz'),
        ('SO', 'Soleure'),
        ('TI', 'Tessin'),
        ('TG', 'Thurgovie'),
        ('UR', 'Uri'),
        ('VS', 'Valais'),
        ('VD', 'Vaud'),
        ('ZG', 'Zoug'),
        ('ZH', 'Zurich'),
    ):
        canton = Canton(iso=iso, name_fr=name_fr)
        canton.save()

    with open('gentile.csv', 'r') as input:
        for line in input.readlines():
            canton_str, commune_str, gentile_str = line.split(';')
            gentile_str = gentile_str[:-1]  # Remove trailing '\n'

            commune = Commune(
                name_fr=commune_str,
                gentile_fr=gentile_str
            )
            commune.canton = Canton.objects.get(name_fr=canton_str)
            commune.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gentile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_from_data),
    ]
