# Generated by Django 4.0.3 on 2022-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentile', '0002_auto_20220324_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='searchable_gentile',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commune',
            name='searchable_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
