# Generated by Django 4.0.3 on 2022-04-07 15:38

from django.db import migrations

from unidecode import unidecode


def populate_searchable_fields(apps, schema_editor):
    Commune = apps.get_model('gentile', 'Commune')

    def generate_searchable_string(string: str):
        return (
            unidecode(string)
            .replace('-', ' ')
            .replace(',', '')
            .replace('Saint', 'saint st')
            .lower()
        )

    for commune in Commune.objects.all():
        commune.searchable_name = generate_searchable_string(commune.name_fr)
        commune.searchable_gentile = generate_searchable_string(commune.gentile_fr)
        commune.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gentile', '0003_commune_searchable_gentile_commune_searchable_name'),
    ]

    operations = [
        migrations.RunPython(populate_searchable_fields)
    ]
